"""empty message

Revision ID: 30857e37d1f1
Revises: eeac5d0aed78
Create Date: 2023-02-20 15:47:41.899436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30857e37d1f1'
down_revision = 'eeac5d0aed78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
